# Site settings
title: Maptime Sacramento
email: sacramento@maptime.io
description: > # this means to ignore newlines until "baseurl:"
 Maptime is, rather literally, time for mapmaking. Our mission is to open the doors of cartographic possibility to anyone interested by creating a time and space for collaborative learning, exploration, and map creation using mapping tools and technologies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: maptimesac


# Build settings
markdown: kramdown
